### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException getAllCategories

### ISSUE THREAD

**Issue by robl2e** [Codepath-Group7/Group7#31]
```
10-18 07:38:28.959 29839-29839/com.codepath.com.sffoodtruck E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.codepath.com.sffoodtruck, PID: 29839
                                                                              java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-2
                                                                                  at java.lang.String.startEndAndLength(String.java:298)
                                                                                  at java.lang.String.substring(String.java:1087)
                                                                                  at com.codepath.com.sffoodtruck.data.model.Business.getAllCategories(Business.java:142)
                                                                                  at com.codepath.com.sffoodtruck.ui.businessdetail.BusinessDetailFragment.renderBusiness(BusinessDetailFragment.java:125)
                                                                                  at com.codepath.com.sffoodtruck.ui.businessdetail.BusinessDetailPresenter$1.onResponse(BusinessDetailPresenter.java:59)
                                                                                  at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by akshaymathur90** [comment]
fixed as part of search-feature
